### ISSUE TITLE
Render JSON replies onto a new page / tab

### ISSUE THREAD

**Issue by sudheesh001** [Orbiter/loklak#1]
Currently searching for a specific hashtag in the loklak application present at loklak.net renders the json replies on the same page after scraping, this makes the user experience of the users who use the website need to go back and sometimes seem lost. Personally as a UX guy I don't  really like a page which seems like a flat dead end. Maybe if we move the result to a new page, users who generally keep tabs open would jump back and use the application again.

https://github.com/Orbiter/loklak/blob/b7bc8aace7c6870b68dabd70ba41d32bdee4445f/html/index.html#L73
looks like the only place where the change has to happen. Maybe if we consider that it should open in a new tab, this could go ahead for a patch.

**Comment by Orbiter** [comment]
implemented as suggested
