### ISSUE TITLE
Implement minified as new parameter to request for minified JSON response

### ISSUE THREAD

**Issue by sudheesh001** [Orbiter/loklak#4]
The current parameters in the API request are `http://loklak.net/api/search.json?q=fossasia&source=twitter` which gives an un minified JSON response to the requester, In cases of large JSON responses, minifying the responses would be a great idea before serving it as the requested information to the client. Here's an example

`http://loklak.net/api/search.json?q=fossasia&source=twitter` 
##### Minified JSON size : 18KB

A possible implementation to the API is a new parameter `minified` holding a boolean response
`http://loklak.net/api/search.json?q=fossasia&source=twitter&minified=true` or
`http://loklak.net/api/search.json?q=fossasia&source=twitter&minified=1`

**Comment by Orbiter** [comment]
good idea, just pushed the feature
